sl_index:
    path:     /
    defaults: { _controller: SLDataHarvestBundle:Default:index }
sl_harvest_index:
    path:     /harvest/{source}
    defaults: { _controller: SLDataHarvestBundle:Default:harvest }
sl_fetch_index:
    path:     /fetch/{source}
    defaults: { _controller: SLDataHarvestBundle:Default:fetch }
sl_filter_tags_index:
    path:     /filter_tags/{year}
    defaults: { _controller: SLDataHarvestBundle:Default:filterTags }